package com.grudus.planshboard.commons.validation

object ValidationKeys {
    const val GAME_ALREADY_EXISTS = "BOARD_GAME.EXISTS"
    const val USER_ALREADY_EXISTS = "USER.EXISTS"
    const val EMPTY_FIELD = "FIELD.EMPTY"
    const val PASSWORD_MISMATCH = "PASSWORD.MISMATCH"
    const val FORBIDDEN = "FORBIDDEN"
    const val OPPONENT_ALREADY_EXISTS = "OPPONENT_ALREADY_EXISTS"
    const val UNKNOWN_USER = "UNKNOWN_USER"
    const val USER_ALREADY_LINKED = "USER_ALREADY_LINKED"
    const val INVALID_BOARD_GAME = "INVALID_BOARD_GAME"
    const val INVALID_POSITION = "INVALID_POSITION"
    const val INVALID_OPPONENT = "INVALID_OPPONENT"

    const val CANNOT_PARTICIPE_IN_PLAY = "CANNOT_PARTICIPE_IN_PLAY"
}
